Repository ros-planning/moveit, pull requests merged in 2019-07, with the labels that each got.

#1508 Select time parametrization algorithm in retime_trajectory
  moveit_commander/src/moveit_commander/move_group.py
  moveit_commander/test/CMakeLists.txt
  moveit_commander/test/python_time_parameterization.py
  moveit_commander/test/python_time_parameterization.test
  moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
Labels: awaits 2nd review

#1539 backport #1538 trajectory recording / memory leak
  moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_representation.h
  moveit_ros/planning/plan_execution/src/plan_execution.cpp
Labels: Melodic

#1555 add RobotTrajectory::getDuration() (#1554)
  moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h
  moveit_core/robot_trajectory/src/robot_trajectory.cpp
Labels: Melodic, backport

#1566 Ensure that if time parameterization fails, error is appropriately propogated (#1562)
  moveit_ros/planning/planning_request_adapter_plugins/src/add_iterative_spline_parameterization.cpp
  moveit_ros/planning/planning_request_adapter_plugins/src/add_time_optimal_parameterization.cpp
  moveit_ros/planning/planning_request_adapter_plugins/src/add_time_parameterization.cpp
Labels: Melodic, backport

#1574 Use portable string() on filesystem::path. (#1571)
  moveit_setup_assistant/src/tools/moveit_config_data.cpp
  moveit_setup_assistant/src/widgets/configuration_files_widget.cpp
  moveit_setup_assistant/src/widgets/start_screen_widget.cpp
Labels: master
