Repository ros-planning/moveit, pull requests merged in 2020-10, with the labels that each got.

#2340 [fix] Segfault when editing pose in moveit_setup_assistant
  moveit_setup_assistant/src/widgets/robot_poses_widget.cpp
Labels: bug, simple improvements

#2347 fix planning python scene namespacing
  moveit_commander/src/moveit_commander/planning_scene_interface.py
  moveit_commander/test/python_moveit_commander_ros_namespace.py
  moveit_commander/test/python_moveit_commander_ros_namespace.test
Labels: awaits 2nd review

#2360 [backport] Let the max number of contacts be the amount of world objects + link models with geometry
  moveit_ros/move_group/CMakeLists.txt
  moveit_ros/move_group/src/default_capabilities/state_validation_service_capability.cpp
  moveit_ros/move_group/test/test_check_state_validity_in_empty_scene.py
  moveit_ros/move_group/test/test_check_state_validity_in_empty_scene.test
Labels: backport, kinetic

#2363 Make GILReleaser exception-safe
  moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
  moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/gil_releaser.h
Labels: awaits 2nd review
