Repository ros-planning/moveit, pull requests merged in 2020-08, with the labels that each got.

#1866 Fix subframes disappearing when object is detached/scaled/renamed
  moveit_core/planning_scene/src/planning_scene.cpp
  moveit_core/robot_state/include/moveit/robot_state/attached_body.h
  moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp
Labels: awaits 2nd review

#2242 Add planning_adapters for chomp in setup assistant
  moveit_setup_assistant/templates/moveit_config_pkg_template/launch/chomp_planning_pipeline.launch.xml
Labels: awaits 2nd review

#2199 Adapt repository for new moveit_resources layout
  moveit_commander/package.xml
  moveit_commander/test/CMakeLists.txt
  moveit_commander/test/python_moveit_commander.test
  moveit_commander/test/python_moveit_commander_ns.test
  moveit_commander/test/python_time_parameterization.test
  moveit_core/collision_detection/include/moveit/collision_detection/test_collision_common_panda.h
  moveit_core/collision_detection/include/moveit/collision_detection/test_collision_common_pr2.h
  moveit_core/collision_detection_bullet/CMakeLists.txt
  moveit_core/collision_detection_bullet/test/test_bullet_continuous_collision_checking.cpp
  moveit_core/collision_detection_fcl/CMakeLists.txt
  moveit_core/collision_distance_field/CMakeLists.txt
  moveit_core/collision_distance_field/test/test_collision_distance_field.cpp
  moveit_core/constraint_samplers/CMakeLists.txt
  moveit_core/kinematic_constraints/CMakeLists.txt
  moveit_core/package.xml
  moveit_core/planning_scene/CMakeLists.txt
  moveit_core/planning_scene/test/test_planning_scene.cpp
  moveit_core/robot_model/CMakeLists.txt
  moveit_core/robot_state/CMakeLists.txt
  moveit_core/robot_state/test/test_aabb.cpp
  moveit_core/robot_state/test/test_cartesian_interpolator.cpp
  moveit_core/robot_state/test/test_kinematic_complex.cpp
  moveit_core/robot_trajectory/CMakeLists.txt
  moveit_core/trajectory_processing/CMakeLists.txt
  moveit_core/utils/include/moveit/utils/robot_model_test_utils.h
  moveit_core/utils/src/robot_model_test_utils.cpp
  moveit_kinematics/package.xml
  moveit_kinematics/test/CMakeLists.txt
  moveit_kinematics/test/fanuc-ikfast.test
  moveit_kinematics/test/fanuc-kdl.test
  moveit_kinematics/test/panda-ikfast.test
  moveit_kinematics/test/panda-kdl.test
  moveit_planners/ompl/ompl_interface/CMakeLists.txt
  moveit_planners/ompl/ompl_interface/test/test_state_space.cpp
  moveit_planners/ompl/package.xml
  moveit_planners/trajopt/test/trajectory_test.test
  moveit_ros/benchmarks/examples/demo_fanuc.launch
  moveit_ros/benchmarks/examples/demo_panda.launch
  moveit_ros/benchmarks/examples/demo_panda_all_planners.launch
  moveit_ros/benchmarks/examples/demo_panda_all_planners_obstacles.launch
  moveit_ros/benchmarks/examples/demo_panda_predefined_poses.launch
  moveit_ros/move_group/package.xml
  moveit_ros/move_group/test/test_cancel_before_plan_execution.test
  moveit_ros/moveit_servo/package.xml
  moveit_ros/moveit_servo/test/servo_cpp_interface_test.test
  moveit_ros/planning/launch/collision_checker_compare.launch
  moveit_ros/planning/planning_components_tools/src/compare_collision_speed_checking_fcl_bullet.cpp
  moveit_ros/planning_interface/package.xml
  moveit_ros/planning_interface/test/CMakeLists.txt
  moveit_ros/planning_interface/test/cleanup.test
  moveit_ros/planning_interface/test/move_group_interface_cpp_test.test
  moveit_ros/planning_interface/test/move_group_pick_place_test.test
  moveit_ros/planning_interface/test/moveit_cpp_test.test
  moveit_ros/planning_interface/test/python_move_group.test
  moveit_ros/planning_interface/test/python_move_group_ns.test
  moveit_ros/planning_interface/test/robot_state_update.test
  moveit_setup_assistant/CMakeLists.txt
  moveit_setup_assistant/package.xml
  moveit_setup_assistant/templates/moveit_config_pkg_template/launch/run_benchmark_trajopt.launch
  moveit_setup_assistant/test/moveit_config_data_test.cpp
Labels: help wanted

#2278 Cleanup: Add a utility to print collision pairs
  moveit_core/collision_detection/CMakeLists.txt
  moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h
  moveit_core/collision_detection/src/collision_common.cpp
Labels: awaits 2nd review

#2282 Update xacro
  moveit_planners/chomp/chomp_interface/test/rrbot_move_group.launch
Labels: awaits 2nd review

#2283 [maint] adjust code coverage yaml to make it more forgiving
  codecov.yaml
Labels: needs discussion
