Repository ros-planning/moveit, pull requests merged in 2020-09, with the labels that each got.

#2277 Melodic backports in ompl interface (cleanup)
  moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/constrained_goal_sampler.h
  moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/state_validity_checker.h
  moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h
  moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/model_based_state_space.h
  moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/work_space/pose_model_state_space.h
  moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/planning_context_manager.h
  moveit_planners/ompl/ompl_interface/src/constraints_library.cpp
  moveit_planners/ompl/ompl_interface/src/detail/constrained_goal_sampler.cpp
  moveit_planners/ompl/ompl_interface/src/detail/constrained_valid_state_sampler.cpp
  moveit_planners/ompl/ompl_interface/src/detail/state_validity_checker.cpp
  moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp
  moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp
  moveit_planners/ompl/ompl_interface/src/ompl_planner.cpp
  moveit_planners/ompl/ompl_interface/src/ompl_planner_manager.cpp
  moveit_planners/ompl/ompl_interface/src/parameterization/model_based_state_space.cpp
  moveit_planners/ompl/ompl_interface/src/parameterization/work_space/pose_model_state_space.cpp
  moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp
Labels: awaits 2nd review, backport

#2306 [maint] Remove patch status from codecov
  codecov.yaml
Labels: simple improvements

#2307 [fix] Servo heap-buffer-overflow bug
  moveit_ros/moveit_servo/src/servo_calcs.cpp
Labels: awaits 2nd review, bug

#2314 Fix Servo interruption
  moveit_ros/moveit_servo/include/moveit_servo/collision_check.h
  moveit_ros/moveit_servo/include/moveit_servo/servo.h
  moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
  moveit_ros/moveit_servo/src/collision_check.cpp
  moveit_ros/moveit_servo/src/cpp_interface_example/cpp_interface_example.cpp
  moveit_ros/moveit_servo/src/servo.cpp
  moveit_ros/moveit_servo/src/servo_calcs.cpp
  moveit_ros/moveit_servo/src/servo_server.cpp
  moveit_ros/moveit_servo/test/servo_cpp_interface_test.cpp
Labels: awaits 2nd review
