Repository ros-planning/moveit, pull requests merged in 2020-03, with the labels that each got.

#1892 Add initial poses to fake_controllers.yaml
  moveit_setup_assistant/src/tools/moveit_config_data.cpp
  moveit_setup_assistant/src/widgets/robot_poses_widget.cpp
Labels: awaits 2nd review

#1890 Add default velocity/acceleration scaling factors
  MIGRATION.md
  moveit_commander/src/moveit_commander/move_group.py
  moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
  moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
  moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
  moveit_setup_assistant/src/tools/moveit_config_data.cpp
Labels: awaits 2nd review

#1949 Implementation of parameter TranslationXY2D IKFast
  moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp
Labels: awaits 2nd review

#1952 Do not override empty URDF link collision geometry
  MIGRATION.md
  moveit_core/robot_model/src/robot_model.cpp
Labels: awaits 2nd review

#1968 fix SINGLE distance checks
  moveit_core/collision_detection_fcl/src/collision_common.cpp
Labels: awaits 2nd review, backport, melodic

#1967 MP display: change internal shortcut Ctrl+R to Ctrl+I
  moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
Labels: awaits 2nd review

#1999 update/adjust keys to satisfy travis config validator
  .travis.yml
Labels: ci
